version: '3'

services:
    http_server:
        build: ./http_server/
        restart: always
        environment:
            NVR_TOKEN: ${NVR_TOKEN}
            SSL_KEY: ${SSL_KEY}
            SSL_CERT: ${SSL_CERT}
            PORT: 443
        ports:
            - "443:443"

    media_server:
        build: ./media_server/
        restart: always
        environment:
            NVR_TOKEN: ${NVR_TOKEN}
            SSL_KEY: ${SSL_KEY}
            SSL_CERT: ${SSL_CERT}
            PORT: 8181
        ports:
            - "8181:8181"
